/**
 * Custom development server used to inject https
 */
const { createServer } = require("https");
const { parse } = require("url");
const next = require("next");
const fs = require("fs");

const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

// setup our dev https options
// these files are generated by running the local setup
const httpsOptions = {
    key: fs.readFileSync("./.local-dev-secrets/key.pem"),
    cert: fs.readFileSync("./.local-dev-secrets/cert.pem")
};

// setup our custom nextjs app with https
app.prepare().then(() => {

    createServer(httpsOptions, (req, res) => {

        const parsedUrl = parse(req.url, true);
        handle(req, res, parsedUrl);

    }).listen(3000, err => {
        if (err) {
            throw err;
        }
        console.log("> Ready on https://localhost:3000");
    });
});
